wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/Makefile
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/dyn_array_time.c
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/better_malloc.c
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/better_malloc_li.c
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/better_malloc_float.c
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/better_malloc_double.c
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/argc_argv.c
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/argc_argv_mod.c
rm setup.sh
