wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/Makefile
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/stat_dyn_func.c
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/dyn_array.c
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/dyn_array_reg.c
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/dyn_array_stat.c
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/stat_array.c
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/stat_array_reg.c
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/fact_int.c
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/fact_float.c
wget https://raw.githubusercontent.com/mmorri22/cse20133/main/inclass/lec19/fact_double.c
rm setup.sh