# Author: 
# E-mail: 
#
# This is the Makefile for the Lecture 8 Example.

# gcc is for the compiler for C


# CFLAGS are the compiler flags for when we compile C code in this course


# Create the Pallel Lib Library


# Create the Pallel Run


# Parallel Program Objects

#Executables


# Executable Names


# Make all


# Make clean

